### ISSUE TITLE
pip : No distributions at all found for modoboa-dmarc

### ISSUE THREAD

**Issue by calvin-86** [modoboa/modoboa-dmarc#1]
debug log for failure in /root/.pip/pip.log :
------------------------------------------------------------
/usr/bin/pip run on Fri Feb 26 19:16:04 2016
Downloading/unpacking modoboa-dmarc
  Getting page https://pypi.python.org/simple/modoboa-dmarc/
  Could not fetch URL https://pypi.python.org/simple/modoboa-dmarc/: 404 Client Error: Not Found
  Will skip URL https://pypi.python.org/simple/modoboa-dmarc/ when looking for download links for modoboa-dmarc
  Getting page https://pypi.python.org/simple/
  URLs to search for versions for modoboa-dmarc:
  * https://pypi.python.org/simple/modoboa-dmarc/
  Getting page https://pypi.python.org/simple/modoboa-dmarc/
  Could not fetch URL https://pypi.python.org/simple/modoboa-dmarc/: 404 Client Error: Not Found
  Will skip URL https://pypi.python.org/simple/modoboa-dmarc/ when looking for download links for modoboa-dmarc
  Could not find any downloads that satisfy the requirement modoboa-dmarc
Cleaning up...
No distributions at all found for modoboa-dmarc
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1178, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 277, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
DistributionNotFound: No distributions at all found for modoboa-dmarc

**Comment by tonioo** [comment]
This plugin is not available on PyPI yet. Do you need it ?

**Comment by calvin-86** [comment]
Well not for a month or so (just add a note to readme that it is not available yet).
I tried to build/install it but I forgot about:
> If you choose to install extensions one at a time, you will have to add their names in settings.py to MODOBOA_APPS. **Also ensure that you have the line from modoboa_amavis.settings import * at the end of this file.**

I will try again this week and will report success/failure. Or is it not production ready ?

**Comment by tonioo** [comment]
It can already be used in production but I must add some documentation.

**Comment by tonioo** [comment]
@calvin-86 I added some documentation to the README file.

**Comment by tonioo** [comment]
@calvin-86 I just release 0.1.0 version.
