### ISSUE TITLE
dmarc extension and postfix

### ISSUE THREAD

**Issue by Toniob** [modoboa/modoboa-dmarc#13]
Hi,

It seems that the postfix integration doesn't work with some checks.
I have to remove `reject_unverified_recipient` in the `smtpd_recipient_restrictions` section. If I don't do it, sending emails to the dmarc account doesn't work : 

> Recipient address rejected: unverified address: unknown mail transport error;

Any idea ?

**Comment by tonioo** [comment]
Looks like you have a configuration issue. Can you paste your postfix configuration somewhere?

**Comment by Toniob** [comment]
https://gist.github.com/Toniob/4c87219b55e9b0b88e8d46c9db398639

**Comment by tonioo** [comment]
Have you run the postmap command on your transport table? (and reload
postfix)

**Comment by Toniob** [comment]
Yep, of course.
If I test without `reject_unverified_recipient`, it works. If I put it back, I've got the error.

**Comment by tonioo** [comment]
That's strange, I have the exact same configuration and it works.

Can you try to remove the /var/lib/postfix/verify_cache.db file and try
again please?

**Comment by Toniob** [comment]
It worked. Thanks a lot and sorry for the noise.
