### ISSUE TITLE
DNS lookup very slow, runs into timeout

### ISSUE THREAD

**Issue by mundschenk-at** [modoboa/modoboa-dmarc#14]
I tried setting up the (reverse) DNS lookup for DMARC reports, but report generation is so slow that it runs into a timeout. Is there any way to optimize the lookup speed to get this to become usable?

**Comment by tonioo** [comment]
The best would be to implement async. lookups, maybe when reports are parsed, and store the result into the database.

**Comment by mundschenk-at** [comment]
That would be a nice solution. Any way I can help with this feature? Unfortunately, my Python knowledge is pretty rusted and I don't know Django at all, but if you point me in the right direction ...

**Comment by mundschenk-at** [comment]
(BTW: I just increased all nginx timeouts to 300s and now the request fails with "Internal Error")

**Comment by mundschenk-at** [comment]
I've experimented some more. The problem does not seem to be the DNS lookups. Instead, it looks like the report import via IMAP somehow messed up the database for that domain. We have not yet had the time to look deeper, but other domains that were not imported do not display the errant behavior.

**Comment by mundschenk-at** [comment]
The problem are IPs without valid reverse DNS - the default timeout for the resolver is 30 seconds. PR #17 tries to fix that.
