### ISSUE TITLE
Should I put this ':' at the end of dmarc-rua-parser

### ISSUE THREAD

**Issue by themsay** [modoboa/modoboa-dmarc#19]
I do not see DMARC on my mail headers.

Following the doc for /etc/postfix/dmarc_transport 
```
<email address your declared in your DNS record>  dmarc-rua-parser:
```

I did this including <code>:</code> at the end
```
echo "reports@example.com  dmarc-rua-parser:" > /etc/postfix/dmarc_transport
```
<code>$ postmap /etc/postfix/dmarc_transport</code>

DNS record
```
_dmarc.example.com.	300	IN	TXT	"_dmarc v=DMARC1\; p=none\; rua=mailto:reports@example.com"
```
I installed with <code>sudo ./run.py example.com</code>
I thinking of replacing ```_dmarc.example.com.``` with ```_dmarc.mail.example.com.```

Any suggestion will be helpful!
Thank you.

**Comment by tonioo** [comment]
@themsay This plugin only parses reports sent by other MTA to build statistics. It does not verify that messages are compliant with dmarc policies. You should take a look at opendmarc.

**Comment by themsay** [comment]
@tonioo Thanks for the clarification. I will checkout opendmarc.
