### ISSUE TITLE
Ask: Multi-Domain Support?

### ISSUE THREAD

**Issue by cremesk** [modoboa/modoboa-dmarc#36]
What do i need for Multi-Domain Support?
It is nesessary to modify '/etc/postfix/dmarc_transport' with the following content?

```
hostmaster@domain1.com  dmarc-rua-parser:
hostmaster@domain2.com  dmarc-rua-parser:
```

Thanks!

**Comment by tonioo** [comment]
@cremesk yes, you need one entry per email address you defined in your DNS records.

**Comment by AmazingBeu** [comment]
You may also only have one mail address to receive reports, but you must define in your receiving domain the domains for which you are allowing the receipt of reports . For exemple : 


**/etc/postfix/dmarc_transport**
```
hostmaster@domain1.com  dmarc-rua-parser:
```

**domain2.com DNS records:**
```
_report._dmarc.domain2.com.           TXT          "v=DMARC1; p=quarantine; pct=100; rua=mailto:hostmaster@domain1.com; ruf=mailto:hostmaster@domain1.com"
```

**domain1.com DNS records:**
```
domain2.com._report._dmarc.domain1.com.                 TXT           "v=DMARC1"
```

For more information, read this : https://tools.ietf.org/html/rfc7489#appendix-B.2.3
