### ISSUE TITLE
Setup incompatible with PIP 20.0.2+

### ISSUE THREAD

**Issue by PatTheMav** [modoboa/modoboa-dmarc#40]
Starting with PIP versions after 20.0.2, any setup scripts relying on PIP internals will fail, as the internals have changed.
This part will now fail, as `parse_requirements` returns a new `ParsedRequirement` object which contains the expected `requirements` property, so `match_markers` is not available:

```
    if path.isfile(requirements_file):
        for req in parse_requirements(requirements_file, session="hack"):
            # check markers, such as
            #
            #     rope_py3k    ; python_version >= '3.0'
            #
            if req.match_markers():
                requirements.append(str(req.req))
```

Changing to `req.requirements.match_markers()` (and all consecutive calls) should fix this.

**Comment by tonioo** [comment]
@PatTheMav Thank you!

**Comment by PatTheMav** [comment]
@tonioo You're welcome - if I'm not mistaken you might need to fix this on the other modules as well, just FYI.
