### ISSUE TITLE
Permission denied in virtualenv

### ISSUE THREAD

**Issue by JeroenvO** [modoboa/modoboa-dmarc#6]
I run python from virtualenv and get  fatal: `pipe_command: execvp /srv/modoboa/env/bin/python: Permission denied.`

I use:
```
 dmarc-rua-parser unix  -       n       n       -       -       pipe
  flags= user=vmail:vmail argv=/srv/modoboa/env/bin/python /srv/modoboa/<my hostname>/manage.py import_aggregated_report --pipe
```
The python and manage.py files have execute rights for world.

Do you have any suggestions?

**Comment by tonioo** [comment]
Can you check the permissions of the settings.py file ?

**Comment by JeroenvO** [comment]
The /modoboa/ folder had the wrong permissions. It seems to be working now, thanks for the help!
