### ISSUE TITLE
gzip  files

### ISSUE THREAD

**Issue by Menta2L** [modoboa/modoboa-dmarc#7]
Some of the reporters sends the reports in gzip archive and such a reports are not parsed at all.

Basically its a future request to add a support for gzip archive  for the parser.

**Comment by tonioo** [comment]
Indeed, the parser only supports zip files atm. Do you know a provider who sends reports in gzip format?

**Comment by Menta2L** [comment]
Yes i have several reporters who send me an gzip  formated files. The big one are 
aol.com and mail.ru.

**Comment by Menta2L** [comment]
Actually that is the full list i have at the moment.
aol.com
comcast.com
mail.ru
fastmail.com
dhl.com
iabank.bg
magna.com
italiaonline.it

They all send the reports in gzip format

**Comment by kryskool** [comment]
In RFC 7489 section 7.2.1.1.  Email

> The aggregate data MUST be an XML file that SHOULD be subjected to
> GZIP compression.  Declining to apply compression can cause the
> report to be too large for a receiver to process (a commonly observed
> receiver limit is ten megabytes); doing the compression increases the
> chances of acceptance of the report at some compute cost.  The
> aggregate data SHOULD be present using the media type "application/
> gzip" if compressed (see [GZIP]), and "text/xml" otherwise.

The xml file is not necessary compressed, valid extension are **.xml .xml.gz .zip**
