### ISSUE TITLE
opendkim and dmarc

### ISSUE THREAD

**Issue by JayBeRayBearGun** [modoboa/modoboa-dmarc#8]
After some commandline tinkering i got opendim working or so it seems. At least 
check-auth@verifier.port25.com seems to agree.

Naturally next I will update postfix (milter) settings and DNS settings to enable dmarc. I noticed there is some support for dmarc in modoboa. Is there anything I should watch out for that I might break through conflicting actions? Or am i safe for now (and how about the future).

**Comment by tonioo** [comment]
The DMARC plugin only generates human-readable reports, using XML reports sent by compatible MTA around the net. It is pretty safe.
Read the README to know how to enable it.

**Comment by JayBeRayBearGun** [comment]
I will, thanks! PS: i saw we have some updates. Again perhaps a trivial questiosn but what is tha adviced/safe way to upgrade? (I used the modoboa installer)

**Comment by tonioo** [comment]
For now, upgrades are manual. The documentation will help you: http://modoboa.readthedocs.io/en/latest/upgrade.html. The 1.6.3 brings a little modification to the SQL schema.

**Comment by JayBeRayBearGun** [comment]
Thanks!
